name:                hanalytics
version:             0.1.0.0
github:              "githubuser/hanalytics"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hanalytics#readme>

dependencies:
- base >= 4.7 && < 5
- smtp-mail >= 0.1.4.6
- aeson >= 1.4.1.0
- bytestring >= 0.10.8.2
- HTTP >= 4000.3.12
- mime-mail >= 0.4.11
- network-uri >= 2.6.1.0
- text >= 1.2.3.1

library:
  source-dirs: src

executables:
  hanalytics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hanalytics

tests:
  hanalytics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hanalytics
